# Generated by Django 4.0.2 on 2022-02-05 22:44

from django.db import migrations, models
import django.db.models.manager
import imgscan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgObject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imgfile', models.FileField(unique=True, upload_to=imgscan.models.imgpath)),
                ('detect', models.BooleanField(default=True)),
                ('scanned', models.DateTimeField(null=True)),
                ('objects', models.ManyToManyField(to='imgscan.ImgObject')),
            ],
            managers=[
                ('dbobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
