# Generated by Django 4.0.2 on 2022-02-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='scanned',
            field=models.DateTimeField(null=True),
        ),
    ]
